# Generated by Django 3.2.5 on 2022-03-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0002_function'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
